apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasksservices
  template:
    metadata:
      labels:
        app: tasksservices
    spec:
      containers:
        - name: tasksservices
          image: abelofficial/tasksservices:latest
