apiVersion: v1
kind: Service
metadata:
  name: tasksnpservices-srv
spec:
  type: NodePort
  selector:
    app: tasksservices
  ports:
    - name: tasksservices
      protocol: TCP
      port: 80
      targetPort: 80
