apiVersion: v1
kind: Service
metadata:
  name: usersnpservices-srv
spec:
  type: NodePort
  selector:
    app: usersservices
  ports:
    - name: usersservices
      protocol: TCP
      port: 80
      targetPort: 80
